version: 2

sources:
  - name: superstore
    description: Data from Superstore dataset
    database: surfalytics_dw_kamil
    schema: stg

    # Adding freshness test for learning purpose, it doesn't make sense for this data.
    config:
      freshness:
        warn_after:
          count: 24
          period: hour
        error_after:
          count: 48
          period: hour
      # Using order_date as the loaded_at_field since it represents data recency
      # For production, you'd typically use an ETL timestamp column
      loaded_at_field: "order_date::timestamp"

    tables:
      - name: orders
        description: Raw orders data
        config:
          # Override default freshness for orders - more strict monitoring
          freshness:
            warn_after:
              count: 12
              period: hour
            error_after:
              count: 24
              period: hour
          loaded_at_field: "order_date::timestamp"

      - name: people
        description: Raw data for regional managers
        config:
          # People table is static reference data - disable freshness check
          freshness: null

      - name: returns
        description: Raw data for returned orders
        config:
          # Returns inherit default freshness settings (24h warn, 48h error)
          loaded_at_field: "order_date::timestamp"
