version: 2

sources:
  - name: superstore
    description: Data from Superstore dataset
    database: surfalytics_dw_kamil
    schema: stg
    tables:
      - name: orders
        description: Raw orders data
      - name: people
        description: Raw data for regional managers
      - name: returns
        description: Raw data for returned orders
