name: dbt_superstore

profile: dbt_superstore

seed-paths: ["seeds"]
model-paths: ["models"]
macro-paths: ["macros"]
clean-targets:
  - "target"
  - "dbt_packages"

seeds:
  # Seeds are for small, static reference data (e.g., calendar, lookup tables)
  # Transactional data should be ingested via source tables
  dbt_superstore:
    +schema: raw

models:
  dbt_superstore:
    # Bronze layer: Staging models (1:1 with source)
    bronze:
      +materialized: view
      +meta:
        layer: bronze
        owner: data_engineering_team
        purpose: staging_layer
        data_quality_tier: raw
        description: "Staging models that perform basic transformations and standardization"

    # Silver layer: Intermediate models with business logic and joins
    silver:
      +materialized: view
      +meta:
        layer: silver
        owner: analytics_team
        purpose: intermediate_layer
        data_quality_tier: enriched
        description: "Intermediate models with joins, enrichments, and derived columns"

    # Examples folder for incremental strategy demonstrations
    examples_incremental_strategies:
      +materialized: incremental
      +meta:
        layer: examples
        owner: data_engineering_team
        purpose: documentation
        data_quality_tier: example
        description: "Example models demonstrating different incremental strategies"

dispatch:
  - macro_namespace: dbt
    search_order: ["dbt_project_evaluator", "dbt"]
