version: 2

models:
  - name: dim_product
    description: "Product dimension table containing unique products with surrogate keys"
    columns:
      - name: product_sk
        description: "Surrogate key for product dimension (generated via dbt_utils.generate_surrogate_key)"
        tests:
          - unique
          - not_null
      - name: product_id
        description: "Natural key - original product identifier"
        tests:
          - unique
          - not_null
      - name: product_name
        description: "Product name"
        tests:
          - not_null
      - name: category
        description: "Product category (e.g., Furniture, Office Supplies, Technology)"
        tests:
          - not_null
      - name: sub_category
        description: "Product sub-category"
        tests:
          - not_null
      - name: etl_timestamp
        description: "Timestamp when record was loaded into Gold layer"
        tests:
          - not_null

  - name: dim_customer
    description: "Customer dimension table containing unique customers with surrogate keys"
    columns:
      - name: customer_sk
        description: "Surrogate key for customer dimension (generated via dbt_utils.generate_surrogate_key)"
        tests:
          - unique
          - not_null
      - name: customer_id
        description: "Natural key - original customer identifier"
        tests:
          - unique
          - not_null
      - name: customer_name
        description: "Customer name"
        tests:
          - not_null
      - name: segment
        description: "Customer segment (Consumer, Corporate, Home Office)"
        tests:
          - not_null
          - accepted_values:
              values: ["Consumer", "Corporate", "Home Office"]
      - name: etl_timestamp
        description: "Timestamp when record was loaded into Gold layer"
        tests:
          - not_null

  - name: dim_shipping
    description: "Shipping dimension table containing unique shipping modes with surrogate keys"
    columns:
      - name: shipping_sk
        description: "Surrogate key for shipping dimension (generated via dbt_utils.generate_surrogate_key)"
        tests:
          - unique
          - not_null
      - name: ship_mode
        description: "Shipping mode/method"
        tests:
          - unique
          - not_null
      - name: etl_timestamp
        description: "Timestamp when record was loaded into Gold layer"
        tests:
          - not_null

  - name: dim_geo
    description: "Geographic dimension table containing unique location combinations with surrogate keys"
    columns:
      - name: geo_sk
        description: "Surrogate key for geographic dimension (generated via dbt_utils.generate_surrogate_key)"
        tests:
          - unique
          - not_null
      - name: country_region
        description: "Country"
        tests:
          - not_null
      - name: city
        description: "City"
        tests:
          - not_null
      - name: state
        description: "State or province"
        tests:
          - not_null
      - name: postal_code
        description: "Postal code"
        tests:
          - not_null
      - name: region
        description: "Sales region"
        tests:
          - not_null
      - name: etl_timestamp
        description: "Timestamp when record was loaded into Gold layer"
        tests:
          - not_null

  - name: fct_sales
    description: "Sales fact table containing transactional metrics with foreign keys to dimension tables"
    columns:
      - name: sales_sk
        description: "Surrogate key for sales fact (generated via dbt_utils.generate_surrogate_key)"
        tests:
          - unique
          - not_null
      - name: product_sk
        description: "Foreign key to dim_product"
        tests:
          - not_null
          - relationships:
              to: ref('dim_product')
              field: product_sk
      - name: customer_sk
        description: "Foreign key to dim_customer"
        tests:
          - not_null
          - relationships:
              to: ref('dim_customer')
              field: customer_sk
      - name: shipping_sk
        description: "Foreign key to dim_shipping"
        tests:
          - not_null
          - relationships:
              to: ref('dim_shipping')
              field: shipping_sk
      - name: geo_sk
        description: "Foreign key to dim_geo"
        tests:
          - not_null
          - relationships:
              to: ref('dim_geo')
              field: geo_sk
      - name: date_id
        description: "Date of the order (foreign key to calendar dimension)"
        tests:
          - not_null
      - name: order_line_id
        description: "Original order line identifier for traceability"
        tests:
          - not_null
      - name: order_id
        description: "Order identifier for grouping order lines"
        tests:
          - not_null
      - name: sales_amt
        description: "Sales amount in USD"
        tests:
          - not_null
          - dbt_utils.expression_is_true:
              expression: ">= 0"
      - name: items_number
        description: "Quantity of items sold"
        tests:
          - not_null
      - name: profit
        description: "Profit from the sale"
      - name: discount
        description: "Discount applied to the sale"
      - name: shipping_cost
        description: "Derived metric: estimated shipping cost"
        tests:
          - not_null
      - name: orders_number
        description: "Count of orders (always 1 at order line grain)"
        tests:
          - not_null
          - accepted_values:
              values: [1]
      - name: cumulative_sales_by_customer
        description: "Window function: cumulative sales for each customer over time"
        tests:
          - not_null
      - name: category_sales_rank
        description: "Window function: rank of sales transactions by amount within each product category"
        tests:
          - not_null
      - name: etl_timestamp
        description: "Timestamp when record was loaded into Gold layer"
        tests:
          - not_null
