dbt_superstore:
  target: dev
  outputs:
    dev:
      type: postgres
      host: surfalytics-prod.postgres.database.azure.com
      port: 5432
      user: surfalyticsadmin
      password: Data2024!
      dbname: surfalytics_dw_kamil
      schema: dev_bronze
      threads: 4
